when:
  - event: tag
    ref: refs/tags/v*

steps: 
  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    settings: 
      repo: github.com/nnuuvv/ionos_ddns_updater_gleam
      registry: ghrc.io
      username: $CI_COMMIT_AUTHOR
      password:
        from_secret: GITHUB_TOKEN
