when:
  - event: tag
    ref: refs/tags/v*

steps: 
  - name: publish
    image: woodpeckerci/plugin-docker-buildx:latest
    settings: 
      repo: github.com/nnuuvv/ionos_ddns_updater_gleam
      tags: latest,$CI_COMMIT_TAG
      registry: ghcr.io
      username: $CI_COMMIT_AUTHOR
      password:
        from_secret: GITHUB_TOKEN
